"""The recording script for training VORTEX's own custom voice
(tools/voice_training/ - see README.md for the full workflow).

SENTENCES is hand-composed, not a named published corpus (e.g. "the Harvard
Sentences") - deliberately not claimed as one, since reproducing that exact
text from memory risked inaccuracy. Designed for the same goal such corpora
serve: broad phoneme/diphone coverage across natural-sounding, ordinary
sentences a person would actually say - short declaratives, questions, and
a few exclamations, varied lengths (4-14 words), no tongue-twisters or
technical jargon that would make recording harder than it needs to be.

155 sentences (~1,090 words total) - roughly 8-12 minutes of pure reading
at a natural pace, likely 15-20 minutes of wall-clock recording time once
pauses between sentences and the occasional re-take are counted. An honest
"first pass" target (see tools/wakeword/build_hey_vortex.py's own module
docstring for the same framing: "a working first pass, not a polished
model"), not a claim this alone produces a great voice. Recording more
sentences later and re-running training with the larger dataset directly
improves quality - see README.md's "Recording more later" section.
"""

SENTENCES = [
    # Short declaratives - everyday statements
    "The sun was setting behind the hills.",
    "She picked up the phone and smiled.",
    "It rained heavily all afternoon.",
    "He forgot where he left his keys.",
    "The coffee was still warm.",
    "They walked slowly along the beach.",
    "A cat was sleeping on the windowsill.",
    "The train arrived a few minutes late.",
    "She closed the book and looked outside.",
    "The garden needed watering again.",
    "He tied his shoes and ran out the door.",
    "The bakery smelled like fresh bread.",
    "A soft breeze moved through the trees.",
    "The children were playing in the yard.",
    "She wrote a short note and left it on the table.",
    "The old clock still kept perfect time.",
    "He poured two cups of tea.",
    "The mountains looked blue in the distance.",
    "A dog barked somewhere down the street.",
    "The lights flickered once and came back on.",
    "She packed her bag the night before.",
    "The river was calm and clear.",
    "He turned the page and kept reading.",
    "The market was busy on Saturday morning.",
    "A single candle lit the room.",
    "The bridge stretched across the valley.",
    "She hummed a tune while cooking dinner.",
    "The store closes early on Sundays.",
    "He waved from across the street.",
    "The snow covered every rooftop in town.",
    "A quiet hum came from the old refrigerator.",
    "The path curved gently through the woods.",
    "She checked the time and hurried along.",
    "The kettle whistled on the stove.",
    "He folded the letter and put it away.",
    "The stars were unusually bright that night.",
    "A warm light spilled out from the kitchen.",
    "The boat drifted quietly on the lake.",
    "She laughed at the joke before he finished it.",
    "The office was empty by six o'clock.",
    # Questions
    "What time does the meeting start?",
    "Have you seen my glasses anywhere?",
    "Why did the power go out again?",
    "Could you pass me the salt, please?",
    "Where did you put the umbrella?",
    "Do you want tea or coffee this morning?",
    "How long has it been raining?",
    "Did you lock the front door?",
    "Who left this note on my desk?",
    "Is the store still open right now?",
    "Can you hear me from over there?",
    "What did she say about the schedule?",
    "When does the next bus arrive?",
    "Are you coming to the party tonight?",
    "Why is the printer not working again?",
    "Should we leave now or wait a bit longer?",
    "Did you finish reading that book yet?",
    "How far is the station from here?",
    "What's the fastest way to get downtown?",
    "Have you tried turning it off and on again?",
    # Exclamations / expressive
    "Watch out, the floor is wet!",
    "That's such a relief to hear!",
    "I can't believe it's already Friday!",
    "Wow, this view is incredible!",
    "Careful, that pan is still hot!",
    "Finally, the rain has stopped!",
    "Look at how big that tree has grown!",
    "That was a fantastic surprise!",
    "Oh no, I think I left the stove on.",
    "This is exactly what I needed today.",
    # Everyday assistant-style phrases
    "Remind me to call the dentist tomorrow.",
    "Set a timer for twenty minutes.",
    "Add milk and eggs to the shopping list.",
    "Play something calm in the background.",
    "Turn the volume down a little.",
    "Let me know when the download finishes.",
    "Send that message once you're ready.",
    "Check the weather before we head out.",
    "Save this file to the desktop.",
    "Open the last document I was working on.",
    "Read that paragraph back to me slowly.",
    "Summarize this in a couple of sentences.",
    "Schedule a reminder for next Monday.",
    "Mute the notifications for an hour.",
    "Search for a nearby coffee shop.",
    "Translate this sentence into French.",
    "Show me the latest headlines.",
    "Calculate the total for these expenses.",
    "Back up these photos before deleting them.",
    "Cancel the alarm I set earlier.",
    # More natural conversational variety
    "I think we should take the scenic route instead.",
    "Honestly, I wasn't expecting that at all.",
    "Let's grab lunch before the meeting starts.",
    "She's been working on that project for weeks.",
    "I'll be there in about ten minutes.",
    "We should probably leave a little earlier next time.",
    "That restaurant downtown is supposed to be really good.",
    "I left my jacket at your place last night.",
    "He mentioned something about a delay this morning.",
    "It's been a long week, honestly.",
    "I'm not sure that's the right approach here.",
    "You might want to double check that number.",
    "That reminds me, I still owe you a call.",
    "It looks like the storm is finally passing.",
    "We ran out of time before finishing the last part.",
    "I'd rather wait until tomorrow to decide.",
    "That's a fair point, I hadn't thought of it that way.",
    "Let's see how it looks once it's finished.",
    "I appreciate you taking the time to explain that.",
    "We can always revisit this later if needed.",
    # Numbers, dates, and practical phrases (useful phoneme coverage)
    "The meeting is scheduled for three thirty.",
    "It costs about twenty dollars altogether.",
    "There are twelve items left in stock.",
    "The flight leaves at seven in the morning.",
    "We moved into this house five years ago.",
    "The package should arrive within two days.",
    "There were about forty people at the event.",
    "The recipe calls for two cups of flour.",
    "It's roughly fifteen minutes from here by car.",
    "The store opens at nine and closes at six.",
    "We've been driving for almost three hours now.",
    "The temperature dropped below freezing overnight.",
    "That version came out back in twenty nineteen.",
    "The total came to just under a hundred dollars.",
    "It only takes about five minutes to set up.",
    # Short, varied closers
    "That should do it for now.",
    "Thanks again for your help earlier.",
    "See you again sometime next week.",
    "Talk to you soon.",
    "Take care of yourself.",
    "Let me know if anything changes.",
    "Good luck with the rest of your day.",
    "That's everything for today.",
    "I'll follow up with you tomorrow.",
    "Sounds good, see you then.",
    # More phonetic variety - less common sounds/clusters
    "The judge questioned the witness carefully.",
    "A strange shadow crossed the wall.",
    "The chef measured the spices precisely.",
    "The thunder rumbled far off in the hills.",
    "A thin layer of frost covered the grass.",
    "The violin played a slow, quiet melody.",
    "The children giggled at the puppet show.",
    "A rough wooden fence lined the field.",
    "The theater was nearly full that evening.",
    "She whispered the answer so no one else could hear.",
    "The mechanic checked the engine twice.",
    "A flock of geese flew south for the winter.",
    "The librarian quietly reshelved the books.",
    "The plumber fixed the leak within an hour.",
    "A gentle knock came from the front door.",
    "The photographer waited for the perfect light.",
    "The blacksmith hammered the metal into shape.",
    "A quick glance told her everything she needed to know.",
    "The archer aimed carefully before releasing the arrow.",
    "The gardener trimmed the hedges along the path.",
]
